name: sharepics
description: "An app to create shareable images from templates."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cross_file: ^0.3.4+1
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  image: ^4.2.0
  image_cropper: ^7.0.5
  path: ^1.9.0
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon-light.png"
  adaptive_icon_background: "#5797DB"
  adaptive_icon_foreground: "assets/icon/icon-foreground.png"
  adaptive_icon_monochrome: "assets/icon/icon-monochrome.png"
  remove_alpha_ios: true
  background_color_ios: "#5797DB"